server:
  port: 8222
spring:
  datasource:
    url: jdbc:h2:mem:student_cruds
    username: root
    password: Badiger
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
